# Generated by Django 5.2.7 on 2025-12-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=150)),
                ('capacidade', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
