# Generated by Django 5.2.7 on 2025-12-14 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sala', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ocupacao', 'Ocupação'), ('ociosidade', 'Ociosidade')], max_length=20)),
                ('data', models.DateField(auto_now_add=True)),
                ('conteudo', models.TextField()),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='sala.sala')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='usuarios.usuario')),
            ],
        ),
    ]
